title: Blog Lerntagebuch Bibliotheks- und Archivinformatik famllr
author: Fabienne Mueller
email: fabienne_mueller@ikmail.com
description: Lerntagebuch Modul Bibliotheks- und Archivinformatik FS2024

# social links
github_username:  famllr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
